blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from blog.views import UserPostListView, UserPostDetailView, add_comment

urlpatterns = patterns('',
                       url(r'^$', UserPostListView.as_view(), name='list_user_posts'),
                       url(r'^(?P<pk>\d+)/$', UserPostDetailView.as_view(), name='detail'),
                       url(r'^(?P<userpost_id>\d+)/add_comment/$', add_comment, name='add_comment')
                       )

miland_blog/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),

    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
)

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
import datetime


class UserPost(models.Model):
    title = models.CharField(u'Заголовок статьи', max_length=250)
    text = models.TextField(u'Текст статьи')
    date = models.DateTimeField(u'Дата публикации статьи', default=datetime.datetime.now())

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    userpost = models.ForeignKey(UserPost)
    text = models.CharField(u'Текст комментария', max_length=200)
    date = models.DateTimeField(u'Дата создания комментария', auto_now_add=True)

    def __unicode__(self):
        return self.text

blog/forms.py
__author__ = 'miland'

from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from  django.template.context import RequestContext
from blog.models import UserPost
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime
from blog.forms import CommentForm


class UserPostListView(ListView):
    model = UserPost
    template_name = 'blog/userpost_list.html'
    context_object_name = 'userposts'

    def get_queryset(self):
        title_presentation = UserPost.objects.filter(date__lte=datetime.datetime.now()).order_by('-date')
        paginator = Paginator(title_presentation, 3)
        page = self.request.GET.get('page')
        try:
            userpost = paginator.page(page)
        except PageNotAnInteger:
            userpost = paginator.page(1)
        except EmptyPage:
            userpost = paginator.page(paginator.num_pages)

        return userpost


class UserPostDetailView(DetailView):
    model = UserPost


def add_comment(request, userpost_id):
    userpost = UserPost.objects.get(pk=userpost_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.userpost_id = userpost_id
            new_comment.save()
            return HttpResponseRedirect(reverse('blog:detail', kwargs={'pk': userpost.id}))
    else:
        form = CommentForm()
    return render_to_response('blog/add_comment.html', {'form': form, 'userpost': userpost},
                              context_instance=RequestContext(request))

blog/templates/blog/add_comment.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form id="add_comment" action="{% url 'blog:add_comment' userpost.id %}" method="post">
    {% csrf_token %}
    <p>Ваш комментарий:</p>
    {{ form.as_p }}
    <p><input type="submit" value="Комментировать"></p>
</form>
</body>
</html>

blog/templates/blog/userpost_detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <title>Подробное описание темы</title>
</head>
<body>
<p>{{ userpost.date }}</p>

<h2><a href={% url 'blog:list_user_posts' %}>{{ userpost.title }}</a></h2>

<p>{{ userpost.text }}</p>

{% for comment in userpost.comment_set.all %}
<p>{{comment.date}}</p>
<p>{{comment.text}}</p>
{% endfor %}
<a href="{% url 'blog:add_comment' userpost.id %}">Добавить комментарий</a>

</body>
</html>

blog/templates/blog/userpost_list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Список тем блога</title>
</head>
<body>
<p>Сегодня уже: {% now "b d D" %}</p>
{% for userpost in userposts %}
    <p>{{ userpost.date }}</p>
    <h2><a href="{% url 'blog:detail' userpost.id %}">{{ userpost.title }}</a></h2>
    <h5>{{ userpost.text|truncatewords:10 }}</h5>
{% empty %}
    <p>Нет постов</p>
{% endfor %}
        {% if userposts.has_previous %}
            <a href="?page={{ userposts.previous_page_number }}">предыдущая</a>
        {% endif %}
            Page {{ userposts.number }} of {{ userposts.paginator.num_pages }}.
        {% if userposts.has_next %}
            <a href="?page={{ userposts.next_page_number }}">следующая</a>
        {% endif %}

</body>
</html>